# Generated by Django 3.1.6 on 2022-06-05 11:12

from django.db import migrations, models
import mapbox_location_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', mapbox_location_field.models.LocationField(map_attrs={'center': (17.031645, 51.106715), 'style': 'mapbox://styles/mightysharky/cjwgnjzr004bu1dnpw8kzxa72'})),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', mapbox_location_field.models.AddressAutoHiddenField(map_id='map')),
                ('county_at', models.CharField(max_length=255)),
                ('facility_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Facility',
                'verbose_name_plural': 'Facilities',
            },
        ),
    ]
